[tool.poetry]
name = "evolver"
version = "0.1.0"
description = ""
authors = ["fernaperg <fernaperg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
arcade = "^2.6.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
